connector.name=postgresql
connection-url=jdbc:postgresql://host.docker.internal:5432/fixcycle_db
connection-user=supabase_user
connection-password=${ENV:SUPABASE_DB_PASSWORD}
case-insensitive-name-matching=true