/**
 * 鍓嶇鎬ц兘鐩戞帶鏁版嵁鏀堕泦API
 * 澶勭悊鏉ヨ嚜瀹㈡埛绔殑鎬ц兘鎸囨爣鏁版嵁
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Supabase瀹㈡埛绔厤?
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// 鎬ц兘鎸囨爣鏁版嵁绫诲瀷
interface PerformanceMetrics {
  navigationStart: number;
  domContentLoaded: number;
  loadEventEnd: number;
  firstPaint: number;
  firstContentfulPaint: number;
  largestContentfulPaint: number;
  cumulativeLayoutShift: number;
  firstInputDelay: number;
  interactionToNextPaint: number;
  dnsLookup: number;
  tcpConnection: number;
  requestDuration: number;
  responseDuration: number;
  scriptExecution: number;
  domParsing: number;
  timeToInteractive: number;
  totalBlockingTime: number;
  apiResponseTimes: Record<string, number[]>;
  componentRenderTimes: Record<string, number[]>;
  userInteractionDelays: number[];
}

interface PerformanceEntry {
  type: string;
  timestamp: number;
  [key: string]: any;
}

interface PerformanceData {
  metrics: PerformanceMetrics;
  entries: PerformanceEntry[];
  userAgent: string;
  timestamp: number;
  sessionId?: string;
  userId?: string;
}

// 鏁版嵁楠岃瘉鍜屾竻?
function validatePerformanceData(data: any): PerformanceData | null {
  if (!data.metrics || !data.entries || !data.timestamp) {
    console.warn('[Performance API] Invalid performance data:', data);
    return null;
  }

  // 楠岃瘉蹇呰瀛楁
  const requiredMetrics = [
    'navigationStart',
    'domContentLoaded',
    'loadEventEnd',
    'firstPaint',
    'firstContentfulPaint',
    'largestContentfulPaint',
  ];

  for (const metric of requiredMetrics) {
    if (typeof data.metrics[metric] !== 'number') {
      console.warn(`[Performance API] Missing or invalid metric: ${metric}`);
      return null;
    }
  }

  // 娓呯悊鏁忔劅淇℃伅
  const cleanedData: PerformanceData = {
    metrics: {
      ...data.metrics,
      apiResponseTimes: cleanApiResponseTimes(data.metrics.apiResponseTimes),
      componentRenderTimes: cleanComponentRenderTimes(
        data.metrics.componentRenderTimes
      ),
    },
    entries: data.entries.map(cleanEntry),
    userAgent: sanitizeUserAgent(data.userAgent),
    timestamp: data.timestamp,
    sessionId: data.sessionId,
    userId: data.userId,
  };

  return cleanedData;
}

function cleanApiResponseTimes(
  times: Record<string, number[]>
): Record<string, number[]> {
  if (!times) return {};

  const cleaned: Record<string, number[]> = {};
  Object.keys(times).forEach(url => {
    // 鍙繚鐣橝PI璺緞锛岀Щ闄ゆ煡璇㈠弬?
    const cleanUrl = url.split('?')[0];
    cleaned[cleanUrl] = times[url].slice(0, 50); // 闄愬埗鏁扮粍闀垮害
  });

  return cleaned;
}

function cleanComponentRenderTimes(
  times: Record<string, number[]>
): Record<string, number[]> {
  if (!times) return {};

  const cleaned: Record<string, number[]> = {};
  Object.keys(times).forEach(component => {
    cleaned[component] = times[component].slice(0, 50); // 闄愬埗鏁扮粍闀垮害
  });

  return cleaned;
}

function cleanEntry(entry: any): PerformanceEntry {
  const cleaned: PerformanceEntry = {
    type: entry.type,
    timestamp: entry.timestamp,
  };

  // 鏍规嵁绫诲瀷淇濈暀鐗瑰畾瀛楁
  switch (entry.type) {
    case 'api_response':
      cleaned.url = entry.url;
      cleaned.duration = entry.duration;
      cleaned.isError = entry.isError;
      break;
    case 'component_render':
      cleaned.componentName = entry.componentName;
      cleaned.duration = entry.duration;
      break;
    case 'user_interaction':
      cleaned.delay = entry.delay;
      break;
  }

  return cleaned;
}

function sanitizeUserAgent(userAgent: string): string {
  // 绉婚櫎鍙兘鐨勬晱鎰熶俊?
  return userAgent.replace(/(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/g, '[IP]');
}

// 鍒涘缓鏁版嵁搴撹〃锛堝鏋滀笉瀛樺湪?
async function ensureTablesExist() {
  try {
    // 妫€鏌ヤ富琛ㄦ槸鍚﹀瓨?
    const { data: tables } = await supabase
      .from('information_schema.tables')
      .select('table_name')
      .eq('table_name', 'performance_metrics');

    if (tables && tables.length > 0) {
      return true;
    }

    // 鍒涘缓鎬ц兘鎸囨爣?
    const createMetricsTableSQL = `
      CREATE TABLE IF NOT EXISTS performance_metrics (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id TEXT,
        user_id TEXT,
        user_agent TEXT,
        timestamp TIMESTAMPTZ NOT NULL,

        -- 椤甸潰鍔犺浇鎸囨爣
        navigation_start BIGINT,
        dom_content_loaded BIGINT,
        load_event_end BIGINT,
        first_paint BIGINT,
        first_contentful_paint BIGINT,
        largest_contentful_paint BIGINT,

        -- Core Web Vitals
        cumulative_layout_shift REAL,
        first_input_delay REAL,
        interaction_to_next_paint REAL,

        -- 缃戠粶鎬ц兘
        dns_lookup BIGINT,
        tcp_connection BIGINT,
        request_duration BIGINT,
        response_duration BIGINT,

        -- JavaScript鎵ц
        script_execution BIGINT,
        dom_parsing BIGINT,

        -- 鐢ㄦ埛浣撻獙鎸囨爣
        time_to_interactive BIGINT,
        total_blocking_time BIGINT,

        -- 鑱氬悎鏁版嵁
        avg_api_response_time REAL,
        avg_component_render_time REAL,
        avg_user_interaction_delay REAL,

        -- 鍏冩暟?
        performance_score INTEGER,
        device_info JSONB,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- 鍒涘缓绱㈠紩
      CREATE INDEX IF NOT EXISTS idx_performance_timestamp ON performance_metrics(timestamp);
      CREATE INDEX IF NOT EXISTS idx_performance_session_id ON performance_metrics(session_id);
      CREATE INDEX IF NOT EXISTS idx_performance_user_id ON performance_metrics(user_id);
      CREATE INDEX IF NOT EXISTS idx_performance_score ON performance_metrics(performance_score);
    `;

    const { error: tableError } = await supabase.rpc('execute_sql', {
      sql: createMetricsTableSQL,
    });
    if (tableError) throw tableError;

    // 鍒涘缓璇︾粏鎸囨爣?
    const createDetailsTableSQL = `
      CREATE TABLE IF NOT EXISTS performance_details (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        metric_id BIGINT REFERENCES performance_metrics(id) ON DELETE CASCADE,
        entry_type TEXT NOT NULL,
        data JSONB,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS idx_performance_details_metric_id ON performance_details(metric_id);
      CREATE INDEX IF NOT EXISTS idx_performance_details_entry_type ON performance_details(entry_type);
    `;

    const { error: detailsError } = await supabase.rpc('execute_sql', {
      sql: createDetailsTableSQL,
    });
    if (detailsError) throw detailsError;

    console.log('[Performance API] Tables created successfully');
    return true;
  } catch (error) {
    console.error('[Performance API] Table creation failed:', error);
    return false;
  }
}

// 璁＄畻鑱氬悎鎸囨爣
function calculateAggregates(metrics: PerformanceMetrics): {
  avgApiResponseTime: number;
  avgComponentRenderTime: number;
  avgUserInteractionDelay: number;
  performanceScore: number;
} {
  // 璁＄畻骞冲潎API鍝嶅簲鏃堕棿
  const apiTimes = Object.values(metrics.apiResponseTimes).flat();
  const avgApiResponseTime =
    apiTimes.length > 0
      ? apiTimes.reduce((sum, time) => sum + time, 0) / apiTimes.length
      : 0;

  // 璁＄畻骞冲潎缁勪欢娓叉煋鏃堕棿
  const renderTimes = Object.values(metrics.componentRenderTimes).flat();
  const avgComponentRenderTime =
    renderTimes.length > 0
      ? renderTimes.reduce((sum, time) => sum + time, 0) / renderTimes.length
      : 0;

  // 璁＄畻骞冲潎鐢ㄦ埛浜や簰寤惰繜
  const avgUserInteractionDelay =
    metrics.userInteractionDelays.length > 0
      ? metrics.userInteractionDelays.reduce((sum, delay) => sum + delay, 0) /
        metrics.userInteractionDelays.length
      : 0;

  // 璁＄畻鎬ц兘鍒嗘暟
  let score = 100;
  if (metrics.firstContentfulPaint > 1800) score -= 20;
  if (metrics.largestContentfulPaint > 2500) score -= 25;
  if (metrics.cumulativeLayoutShift > 0.1) score -= 15;
  if (metrics.firstInputDelay > 100) score -= 20;
  if (metrics.totalBlockingTime > 200) score -= 20;

  return {
    avgApiResponseTime,
    avgComponentRenderTime,
    avgUserInteractionDelay,
    performanceScore: Math.max(0, score),
  };
}

// 鎻掑叆鎬ц兘鏁版嵁
async function insertPerformanceData(data: PerformanceData) {
  try {
    const aggregates = calculateAggregates(data.metrics);

    // 鎻掑叆涓绘寚鏍囨暟?
    const { data: metricData, error: metricError } = await supabase
      .from('performance_metrics')
      .insert({
        session_id: data.sessionId,
        user_id: data.userId,
        user_agent: data.userAgent,
        timestamp: new Date(data.timestamp),

        // 椤甸潰鍔犺浇鎸囨爣
        navigation_start: data.metrics.navigationStart,
        dom_content_loaded: data.metrics.domContentLoaded,
        load_event_end: data.metrics.loadEventEnd,
        first_paint: data.metrics.firstPaint,
        first_contentful_paint: data.metrics.firstContentfulPaint,
        largest_contentful_paint: data.metrics.largestContentfulPaint,

        // Core Web Vitals
        cumulative_layout_shift: data.metrics.cumulativeLayoutShift,
        first_input_delay: data.metrics.firstInputDelay,
        interaction_to_next_paint: data.metrics.interactionToNextPaint,

        // 缃戠粶鎬ц兘
        dns_lookup: data.metrics.dnsLookup,
        tcp_connection: data.metrics.tcpConnection,
        request_duration: data.metrics.requestDuration,
        response_duration: data.metrics.responseDuration,

        // JavaScript鎵ц
        script_execution: data.metrics.scriptExecution,
        dom_parsing: data.metrics.domParsing,

        // 鐢ㄦ埛浣撻獙鎸囨爣
        time_to_interactive: data.metrics.timeToInteractive,
        total_blocking_time: data.metrics.totalBlockingTime,

        // 鑱氬悎鏁版嵁
        avg_api_response_time: aggregates.avgApiResponseTime,
        avg_component_render_time: aggregates.avgComponentRenderTime,
        avg_user_interaction_delay: aggregates.avgUserInteractionDelay,
        performance_score: aggregates.performanceScore,

        // 璁惧淇℃伅
        device_info: {
          userAgent: data.userAgent,
          // 鍙互浠巙serAgent瑙ｆ瀽鏇村璁惧淇℃伅
        },
      }) as any
      .select()
      .single();

    if (metricError) {
      console.error('[Performance API] Metric insert error:', metricError);
      return { success: false, error: metricError.message };
    }

    // 鎻掑叆璇︾粏鎸囨爣鏁版嵁
    if (data.entries.length > 0 && metricData) {
      const details = data.entries.map(entry => ({
        metric_id: metricData.id,
        entry_type: entry.type,
        data: entry,
      }));

      const { error: detailsError } = await supabase
        .from('performance_details')
        .insert(details);

      if (detailsError) {
        console.error('[Performance API] Details insert error:', detailsError);
        // 涓嶈繑鍥為敊璇紝鍥犱负涓绘暟鎹凡缁忔彃鍏ユ垚?
      }
    }

    console.log(
      `[Performance API] Successfully inserted performance data for session ${data.sessionId}`
    );
    return { success: true, metricId: metricData?.id };
  } catch (error) {
    console.error('[Performance API] Insert failed:', error);
    return { success: false, error: 'Database operation failed' };
  }
}

// GET - 鑾峰彇鎬ц兘缁熻鏁版嵁
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const sessionId = searchParams.get('sessionId');
    const userId = searchParams.get('userId');
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');
    const limit = parseInt(searchParams.get('limit') || '100');
    const sortBy = searchParams.get('sortBy') || 'timestamp';

    // 鏋勫缓鏌ヨ
    let query = supabase
      .from('performance_metrics')
      .select('*')
      .order(sortBy, { ascending: false })
      .limit(limit);

    if (sessionId) {
      query = query.eq('session_id', sessionId);
    }

    if (userId) {
      query = query.eq('user_id', userId);
    }

    if (startDate) {
      query = query.gte('timestamp', new Date(startDate).toISOString());
    }

    if (endDate) {
      query = query.lte('timestamp', new Date(endDate).toISOString());
    }

    const { data, error, count } = await query;

    if (error) {
      console.error('[Performance API] Query error:', error);
      return NextResponse.json(
        { success: false, error: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data,
      count: count || data.length,
      summary: generatePerformanceSummary(data),
    });
  } catch (error) {
    console.error('[Performance API] GET failed:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch performance data' },
      { status: 500 }
    );
  }
}

// POST - 鎺ユ敹鎬ц兘鎸囨爣鏁版嵁
export async function POST(request: NextRequest) {
  try {
    // 纭繚琛ㄥ瓨?
    await ensureTablesExist();

    const body = await request.json();
    const performanceData = validatePerformanceData(body);

    if (!performanceData) {
      return NextResponse.json(
        { success: false, error: 'Invalid performance data' },
        { status: 400 }
      );
    }

    // 鎻掑叆鏁版嵁
    const result = await insertPerformanceData(performanceData);

    if (!result.success) {
      return NextResponse.json(
        { success: false, error: result.error },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      message: 'Performance data recorded successfully',
      metricId: result.metricId,
    });
  } catch (error) {
    console.error('[Performance API] POST failed:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to process performance data' },
      { status: 500 }
    );
  }
}

// PUT - 鏇存柊鎬ц兘鏁版嵁锛堣緝灏戜娇鐢級
export async function PUT(request: NextRequest) {
  try {
    const { id, updates } = await request.json();

    if (!id || !updates) {
      return NextResponse.json(
        { success: false, error: 'Missing id or updates' },
        { status: 400 }
      );
    }

    const { data, error } = await supabase
      .from('performance_metrics')
      .update(updates)
      .eq('id', id)
      .select();

    if (error) {
      console.error('[Performance API] Update error:', error);
      return NextResponse.json(
        { success: false, error: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data: data?.[0] || null,
    });
  } catch (error) {
    console.error('[Performance API] PUT failed:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to update performance data' },
      { status: 500 }
    );
  }
}

// DELETE - 鍒犻櫎鎬ц兘鏁版嵁
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    const sessionId = searchParams.get('sessionId');

    let query = supabase.from('performance_metrics');

    if (id) {
      const { error } = await query.delete().eq('id', id);
      if (error) throw error;
      return NextResponse.json({ success: true, message: 'Metric deleted' });
    }

    if (sessionId) {
      const { error } = await query.delete().eq('session_id', sessionId);
      if (error) throw error;
      return NextResponse.json({
        success: true,
        message: 'Session metrics deleted',
      });
    }

    return NextResponse.json(
      { success: false, error: 'Missing id or sessionId' },
      { status: 400 }
    );
  } catch (error) {
    console.error('[Performance API] DELETE failed:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to delete performance data' },
      { status: 500 }
    );
  }
}

// 鐢熸垚鎬ц兘鎽樿
function generatePerformanceSummary(metrics: any[]) {
  if (metrics.length === 0) return {};

  // 璁＄畻鍚勯」鎸囨爣鐨勫钩鍧?
  const averages = {
    firstContentfulPaint: 0,
    largestContentfulPaint: 0,
    cumulativeLayoutShift: 0,
    firstInputDelay: 0,
    timeToInteractive: 0,
    performanceScore: 0,
    avgApiResponseTime: 0,
    avgComponentRenderTime: 0,
  };

  metrics.forEach(metric => {
    averages.firstContentfulPaint += metric.first_contentful_paint || 0;
    averages.largestContentfulPaint += metric.largest_contentful_paint || 0;
    averages.cumulativeLayoutShift += metric.cumulative_layout_shift || 0;
    averages.firstInputDelay += metric.first_input_delay || 0;
    averages.timeToInteractive += metric.time_to_interactive || 0;
    averages.performanceScore += metric.performance_score || 0;
    averages.avgApiResponseTime += metric.avg_api_response_time || 0;
    averages.avgComponentRenderTime += metric.avg_component_render_time || 0;
  });

  const count = metrics.length;
  Object.keys(averages).forEach(key => {
    (averages as any)[key] = (averages as any)[key] / count;
  });

  // 鎬ц兘绛夌骇鍒嗗竷
  const scoreDistribution = {
    excellent: metrics.filter(m => m.performance_score >= 90).length,
    good: metrics.filter(
      m => m.performance_score >= 50 && m.performance_score < 90
    ).length,
    poor: metrics.filter(m => m.performance_score < 50).length,
  };

  return {
    totals: metrics.length,
    averages,
    scoreDistribution,
    dateRange: {
      start: new Date(
        Math.min(...metrics.map(m => new Date(m.timestamp).getTime()))
      ),
      end: new Date(
        Math.max(...metrics.map(m => new Date(m.timestamp).getTime()))
      ),
    },
  };
}

// OPTIONS - CORS鏀寔
export async function OPTIONS(request: NextRequest) {
  return new NextResponse(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    },
  });
}

