/**
 * 鐢ㄦ埛琛屼负鏁版嵁鏀堕泦API绔偣
 * 澶勭悊鏉ヨ嚜鍓嶇鐨勮涓鸿拷韪暟? */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Supabase瀹㈡埛绔厤?const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// 琛屼负浜嬩欢鏁版嵁绫诲瀷
interface BehaviorEvent {
  id: string;
  type: string;
  timestamp: number;
  url: string;
  pageTitle: string;
  userAgent: string;
  screenSize: string;
  viewportSize: string;
  userId?: string;
  sessionId: string;
  element?: string;
  elementId?: string;
  elementClass?: string;
  coordinates?: { x: number; y: number };
  scrollDepth?: number;
  duration?: number;
  metadata?: Record<string, any>;
}

interface BehaviorEventsBatch {
  events: BehaviorEvent[];
  metadata: {
    userAgent: string;
    timestamp: number;
    url: string;
  };
}

// 鏁版嵁楠岃瘉鍜屾竻?function validateAndCleanEvent(event: any): BehaviorEvent | null {
  // 鍩虹瀛楁楠岃瘉
  if (!event.id || !event.type || !event.timestamp || !event.sessionId) {
    console.warn('[Behavior API] Invalid event data:', event);
    return null;
  }

  // 娓呯悊鏁忔劅淇℃伅
  const cleanedEvent: BehaviorEvent = {
    id: event.id,
    type: event.type,
    timestamp: event.timestamp,
    url: sanitizeUrl(event.url),
    pageTitle: event.pageTitle || '',
    userAgent: sanitizeUserAgent(event.userAgent),
    screenSize: event.screenSize || '',
    viewportSize: event.viewportSize || '',
    userId: event.userId,
    sessionId: event.sessionId,
    element: event.element,
    elementId: event.elementId,
    elementClass: event.elementClass,
    coordinates: event.coordinates,
    scrollDepth: event.scrollDepth,
    duration: event.duration,
    metadata: cleanMetadata(event.metadata),
  };

  return cleanedEvent;
}

function sanitizeUrl(url: string): string {
  try {
    const urlObj = new URL(url);
    // 绉婚櫎鏌ヨ鍙傛暟涓殑鏁忔劅淇℃伅
    urlObj.search = '';
    return urlObj.toString();
  } catch {
    return url;
  }
}

function sanitizeUserAgent(userAgent: string): string {
  // 绉婚櫎鍙兘鐨勬晱鎰熶俊?  return userAgent.replace(/(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/g, '[IP]');
}

function cleanMetadata(metadata: any): Record<string, any> | undefined {
  if (!metadata) return undefined;

  const cleaned: Record<string, any> = {};

  // 鐧藉悕鍗曞瓧?  const allowedFields = [
    'eventName',
    'formName',
    'action',
    'method',
    'message',
    'filename',
    'lineno',
    'colno',
    'stack',
  ];

  Object.keys(metadata).forEach(key => {
    if (allowedFields.includes(key)) {
      cleaned[key] = metadata[key];
    }
  });

  return cleaned;
}

// 鎵归噺鎻掑叆鏁版嵁?async function insertEvents(events: BehaviorEvent[]) {
  if (events.length === 0) return { success: true, count: 0 };

  try {
    const { data, error } = await supabase.from('user_behavior_events').insert(
      events.map(event => ({
        event_id: event.id,
        event_type: event.type,
        timestamp: new Date(event.timestamp),
        url: event.url,
        page_title: event.pageTitle,
        user_agent: event.userAgent,
        screen_size: event.screenSize,
        viewport_size: event.viewportSize,
        user_id: event.userId,
        session_id: event.sessionId,
        element: event.element,
        element_id: event.elementId,
        element_class: event.elementClass,
        coordinates_x: event?.x,
        coordinates_y: event?.y,
        scroll_depth: event.scrollDepth,
        duration: event.duration,
        metadata: event.metadata,
      }))
    );

    if (error) {
      console.error('[Behavior API] Database insert error:', error);
      return { success: false, error: error.message, count: 0 };
    }

    console.log(`[Behavior API] Successfully inserted ${events.length} events`);
    return { success: true, count: events.length };
  } catch (error) {
    console.error('[Behavior API] Insert failed:', error);
    return { success: false, error: 'Database operation failed', count: 0 };
  }
}

// 鍒涘缓鏁版嵁搴撹〃锛堝鏋滀笉瀛樺湪?async function ensureTableExists() {
  try {
    // 妫€鏌ヨ〃鏄惁瀛樺湪
    const { data: tables } = await supabase
      .from('information_schema.tables')
      .select('table_name')
      .eq('table_name', 'user_behavior_events');

    if (tables && tables.length > 0) {
      return true;
    }

    // 鍒涘缓?    const createTableSQL = `
      CREATE TABLE IF NOT EXISTS user_behavior_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id TEXT UNIQUE NOT NULL,
        event_type TEXT NOT NULL,
        timestamp TIMESTAMPTZ NOT NULL,
        url TEXT,
        page_title TEXT,
        user_agent TEXT,
        screen_size TEXT,
        viewport_size TEXT,
        user_id TEXT,
        session_id TEXT NOT NULL,
        element TEXT,
        element_id TEXT,
        element_class TEXT,
        coordinates_x INTEGER,
        coordinates_y INTEGER,
        scroll_depth INTEGER,
        duration INTEGER,
        metadata JSONB,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS idx_behavior_events_session_id ON user_behavior_events(session_id);
      CREATE INDEX IF NOT EXISTS idx_behavior_events_event_type ON user_behavior_events(event_type);
      CREATE INDEX IF NOT EXISTS idx_behavior_events_timestamp ON user_behavior_events(timestamp);
      CREATE INDEX IF NOT EXISTS idx_behavior_events_user_id ON user_behavior_events(user_id);
    `;

    const { error } = await supabase.rpc('execute_sql', {
      sql: createTableSQL,
    });

    if (error) {
      console.error('[Behavior API] Table creation error:', error);
      return false;
    }

    console.log('[Behavior API] Table created successfully');
    return true;
  } catch (error) {
    console.error('[Behavior API] Table check/creation failed:', error);
    return false;
  }
}

// GET - 鑾峰彇琛屼负缁熻鏁版嵁
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const sessionId = searchParams.get('sessionId');
    const eventType = searchParams.get('eventType');
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');
    const limit = parseInt(searchParams.get('limit') || '100');

    // 鏋勫缓鏌ヨ鏉′欢
    let query = supabase
      .from('user_behavior_events')
      .select('*')
      .order('timestamp', { ascending: false })
      .limit(limit);

    if (sessionId) {
      query = query.eq('session_id', sessionId);
    }

    if (eventType) {
      query = query.eq('event_type', eventType);
    }

    if (startDate) {
      query = query.gte('timestamp', new Date(startDate).toISOString());
    }

    if (endDate) {
      query = query.lte('timestamp', new Date(endDate).toISOString());
    }

    const { data, error, count } = await query;

    if (error) {
      console.error('[Behavior API] Query error:', error);
      return NextResponse.json(
        { success: false, error: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data,
      count: count || data.length,
      summary: generateSummary(data),
    });
  } catch (error) {
    console.error('[Behavior API] GET failed:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch behavior data' },
      { status: 500 }
    );
  }
}

// POST - 鎺ユ敹琛屼负浜嬩欢鏁版嵁
export async function POST(request: NextRequest) {
  try {
    // 纭繚琛ㄥ瓨?    await ensureTableExists();

    const body: BehaviorEventsBatch = await request.json();

    // 楠岃瘉璇锋眰?    if (!body.events || !Array.isArray(body.events)) {
      return NextResponse.json(
        { success: false, error: 'Invalid events array' },
        { status: 400 }
      );
    }

    // 楠岃瘉鍜屾竻鐞嗕簨浠舵暟?    const validEvents = body.events
      .map(validateAndCleanEvent)
      .filter((event): event is BehaviorEvent => event !== null);

    if (validEvents.length === 0) {
      return NextResponse.json(
        { success: false, error: 'No valid events to process' },
        { status: 400 }
      );
    }

    // 鎻掑叆鏁版嵁
    const result = await insertEvents(validEvents);

    if (!result.success) {
      return NextResponse.json(
        { success: false, error: result.error },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      processed: result.count,
      message: `Successfully processed ${result.count} events`,
    });
  } catch (error) {
    console.error('[Behavior API] POST failed:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to process behavior events' },
      { status: 500 }
    );
  }
}

// PUT - 鏇存柊鐗瑰畾浜嬩欢锛堣緝灏戜娇鐢級
export async function PUT(request: NextRequest) {
  try {
    const { eventId, updates } = await request.json();

    if (!eventId || !updates) {
      return NextResponse.json(
        { success: false, error: 'Missing eventId or updates' },
        { status: 400 }
      );
    }

    const { data, error } = await supabase
      .from('user_behavior_events')
      .update(updates)
      .eq('event_id', eventId)
      .select();

    if (error) {
      console.error('[Behavior API] Update error:', error);
      return NextResponse.json(
        { success: false, error: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data: data?.[0] || null,
    });
  } catch (error) {
    console.error('[Behavior API] PUT failed:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to update behavior event' },
      { status: 500 }
    );
  }
}

// DELETE - 鍒犻櫎鐗瑰畾浜嬩欢锛堣皑鎱庝娇鐢級
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const eventId = searchParams.get('eventId');
    const sessionId = searchParams.get('sessionId');

    let query = supabase.from('user_behavior_events');

    if (eventId) {
      const { error } = await query.delete().eq('event_id', eventId);
      if (error) throw error;
      return NextResponse.json({ success: true, message: 'Event deleted' });
    }

    if (sessionId) {
      const { error } = await query.delete().eq('session_id', sessionId);
      if (error) throw error;
      return NextResponse.json({
        success: true,
        message: 'Session events deleted',
      });
    }

    return NextResponse.json(
      { success: false, error: 'Missing eventId or sessionId' },
      { status: 400 }
    );
  } catch (error) {
    console.error('[Behavior API] DELETE failed:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to delete behavior events' },
      { status: 500 }
    );
  }
}

// 鐢熸垚缁熻鎽樿
function generateSummary(events: any[]) {
  if (events.length === 0) return {};

  const eventTypeCounts: Record<string, number> = {};
  const pageViews: Record<string, number> = {};
  const uniqueSessions = new Set<string>();
  const uniqueUsers = new Set<string>();

  events.forEach(event => {
    // 浜嬩欢绫诲瀷缁熻
    eventTypeCounts[event.event_type] =
      (eventTypeCounts[event.event_type] || 0) + 1;

    // 椤甸潰娴忚缁熻
    if (event.event_type === 'page_view') {
      pageViews[event.url] = (pageViews[event.url] || 0) + 1;
    }

    // 鍞竴浼氳瘽鍜岀敤?    uniqueSessions.add(event.session_id);
    if (event.user_id) {
      uniqueUsers.add(event.user_id);
    }
  });

  return {
    totalEvents: events.length,
    uniqueSessions: uniqueSessions.size,
    uniqueUsers: uniqueUsers.size,
    eventTypeDistribution: eventTypeCounts,
    popularPages: Object.entries(pageViews)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 10)
      .reduce((acc, [url, count]) => ({ ...acc, [url]: count }), {}),
    dateRange: {
      start: new Date(
        Math.min(...events.map(e => new Date(e.timestamp).getTime()))
      ),
      end: new Date(
        Math.max(...events.map(e => new Date(e.timestamp).getTime()))
      ),
    },
  };
}

// 閿欒澶勭悊涓棿?export async function OPTIONS(request: NextRequest) {
  return new NextResponse(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    },
  });
}

